feat: Improve error message formatting
Error message formatting for `see` and `spot` have been by catching chai
assertion errors, formatting them and then re-throwing
This solved the DX issue of hard to read chai errors being re-thrown in
a test suite having backlashes escaped.

Instead of an error that looks like:
```txt
AssertionError: expected '\n------------\ncustom: \\'no breaking change\
\'\n\n\n? Commit or Edit\n❯ Commit\n──────────────\ntype\nscope\nsubject
\nbody\nadd footer\n(Use arrow keys to reveal more choices)' to include
'custom: no breaking change'
```

We now have an error that looks like:
```txt
expected '
------------
custom: \'no breaking change\'

? Commit or Edit
❯ Commit
──────────────
type
scope
subject
body
add footer
(Use arrow keys to reveal more choices)' to include 'custom: no breaking
change'
```

Which is far easier to parse and see how the expected screen differs
from the actual screen